### ISSUE TITLE
ESP32-S3-WROOM-2-N16R8V

### ISSUE THREAD

**Issue by nmcrae85** [ptr727/ESPHome-Config#24]
Hi,

I have an ESP32-S3-WROOM-2-N16R8V. Trying to use this in ESPHome inside home assistant (as an addon).

Im not getting very far and as helpful as your github is im struggling to get any basic config to stick on my ESP. Could really use some help of where to start?

**Comment by ptr727** [comment]
For ESPHome support use their [Discord](https://discord.gg/dbwxp5R3) server.
